### DISCUSSION TITLE
Get lamp state via API

### DISCUSSION THREAD

**Discussion by Floyer007** [easytarget/esp32-cam-webserver#225] [Q&A] [answered]
I would like to see a API get command of the current lamp percentage.
E.g. if no "val" parameter is set or at a special value (e.g. -2).

**Comment by easytarget** [comment, marked as answer]
You can get the lamp value from from the existing status command. 
https://github.com/easytarget/esp32-cam-webserver/blob/master/API.md#examples
The only 'special' value is `-1`, which indicates 'no lamp'. Otherwise zero is off, and the reading is in percentage.

**Reply by Floyer007** [reply]
Thank you for the clarification. Actually overlooked the status feature.

**Reply by Floyer007** [reply]
In case someone wants to create a HomeAssistant switch for it, as I did:

```
- platform: command_line
  switches:
    esplight:
      command_on: "/usr/bin/curl -X GET 'http://IP-ADDRESS/control?var=lamp&val=100'"
      command_off: "/usr/bin/curl -X GET 'http://IP-ADDRESS/control?var=lamp&val=0'"
      command_state: "/usr/bin/curl -X GET http://IP-ADDRESS/status"
      value_template:  "{{value_json.lamp > 0}}"
```
